name: focusboard
description: "FocusBoard — a productivity app combining Kanban boards and the Eisenhower Matrix."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  ## State management + DI
  get: ^4.6.6

  ## Storage
  shared_preferences: ^2.3.2

  ## URL
  url_strategy: ^0.3.0

  ## Font
  google_fonts: ^6.2.1

  ## Icon
  flutter_lucide: ^1.4.0

  ## Other
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
    - assets/data/
